In [6]:
import pandas as pd

In [23]:
df1 = pd.read_csv('data1.csv')
df2 = pd.read_csv('data2.csv')
df3 = pd.read_csv('data3.csv')

In [24]:
df1

       2021-10-24 00:33:00  19  20850235  F      PLAQUETAS SANGUE   316,00
0      2021-10-24 00:33:00  70  16084789  M      PLAQUETAS SANGUE   239,00
1      2021-10-24 00:33:00  62  25926519  F      PLAQUETAS SANGUE   166,00
2      2021-10-24 00:33:00  49  20209887  M      PLAQUETAS SANGUE   201,00
3      2021-10-24 00:33:00  50  25722538  M      PLAQUETAS SANGUE   319,00
4      2021-10-24 00:33:00  19  20850235  F  NEUTRÓFILOS ABSOLUTO   9,9006
...                    ...  ..       ... ..                   ...      ...
69438  2021-12-10 05:44:00  52  14708160  F      PLAQUETAS SANGUE   172,00
69439  2021-12-10 05:44:00  52  14708160  F  NEUTRÓFILOS ABSOLUTO  10,4661
69440  2021-12-10 05:44:00  52  14708160  F   LINFÓCITOS ABSOLUTO   0,3609
69441  2021-12-10 05:44:00  52  14708160  F         NEUTRÓFILOS %     87,0
69442  2021-12-10 05:44:00  52  14708160  F          LINFÓCITOS %      3,0

[69443 rows x 6 columns]

In [26]:
df1.columns = df1.columns.str.lower().str.replace(' ', '_')
df1

       2021-10-24_00:33:00  19  20850235  f      plaquetas_sangue   316,00
0      2021-10-24 00:33:00  70  16084789  M      PLAQUETAS SANGUE   239,00
1      2021-10-24 00:33:00  62  25926519  F      PLAQUETAS SANGUE   166,00
2      2021-10-24 00:33:00  49  20209887  M      PLAQUETAS SANGUE   201,00
3      2021-10-24 00:33:00  50  25722538  M      PLAQUETAS SANGUE   319,00
4      2021-10-24 00:33:00  19  20850235  F  NEUTRÓFILOS ABSOLUTO   9,9006
...                    ...  ..       ... ..                   ...      ...
69438  2021-12-10 05:44:00  52  14708160  F      PLAQUETAS SANGUE   172,00
69439  2021-12-10 05:44:00  52  14708160  F  NEUTRÓFILOS ABSOLUTO  10,4661
69440  2021-12-10 05:44:00  52  14708160  F   LINFÓCITOS ABSOLUTO   0,3609
69441  2021-12-10 05:44:00  52  14708160  F         NEUTRÓFILOS %     87,0
69442  2021-12-10 05:44:00  52  14708160  F          LINFÓCITOS %      3,0

[69443 rows x 6 columns]

In [27]:
df1.rename(columns={'2021-10-24_00:33:00':'date_time'}, inplace=True)

In [28]:
df1

                 date_time  19  20850235  f      plaquetas_sangue   316,00
0      2021-10-24 00:33:00  70  16084789  M      PLAQUETAS SANGUE   239,00
1      2021-10-24 00:33:00  62  25926519  F      PLAQUETAS SANGUE   166,00
2      2021-10-24 00:33:00  49  20209887  M      PLAQUETAS SANGUE   201,00
3      2021-10-24 00:33:00  50  25722538  M      PLAQUETAS SANGUE   319,00
4      2021-10-24 00:33:00  19  20850235  F  NEUTRÓFILOS ABSOLUTO   9,9006
...                    ...  ..       ... ..                   ...      ...
69438  2021-12-10 05:44:00  52  14708160  F      PLAQUETAS SANGUE   172,00
69439  2021-12-10 05:44:00  52  14708160  F  NEUTRÓFILOS ABSOLUTO  10,4661
69440  2021-12-10 05:44:00  52  14708160  F   LINFÓCITOS ABSOLUTO   0,3609
69441  2021-12-10 05:44:00  52  14708160  F         NEUTRÓFILOS %     87,0
69442  2021-12-10 05:44:00  52  14708160  F          LINFÓCITOS %      3,0

[69443 rows x 6 columns]

In [29]:
df1.rename(columns={'19':'age'}, inplace=True)

In [30]:
df1

                 date_time  age  20850235  f      plaquetas_sangue   316,00
0      2021-10-24 00:33:00   70  16084789  M      PLAQUETAS SANGUE   239,00
1      2021-10-24 00:33:00   62  25926519  F      PLAQUETAS SANGUE   166,00
2      2021-10-24 00:33:00   49  20209887  M      PLAQUETAS SANGUE   201,00
3      2021-10-24 00:33:00   50  25722538  M      PLAQUETAS SANGUE   319,00
4      2021-10-24 00:33:00   19  20850235  F  NEUTRÓFILOS ABSOLUTO   9,9006
...                    ...  ...       ... ..                   ...      ...
69438  2021-12-10 05:44:00   52  14708160  F      PLAQUETAS SANGUE   172,00
69439  2021-12-10 05:44:00   52  14708160  F  NEUTRÓFILOS ABSOLUTO  10,4661
69440  2021-12-10 05:44:00   52  14708160  F   LINFÓCITOS ABSOLUTO   0,3609
69441  2021-12-10 05:44:00   52  14708160  F         NEUTRÓFILOS %     87,0
69442  2021-12-10 05:44:00   52  14708160  F          LINFÓCITOS %      3,0

[69443 rows x 6 columns]

In [31]:
df1.rename(columns={'20850235': 'patient_id', 'f': 'gender'}, inplace=True)

In [32]:
df1

,date_time,age,patient_id,gender,plaquetas_sangue,"316,00"
0,2021-10-24 00:33:00,70,16084789,M,PLAQUETAS SANGUE,"239,00"
1,2021-10-24 00:33:00,62,25926519,F,PLAQUETAS SANGUE,"166,00"
2,2021-10-24 00:33:00,49,20209887,M,PLAQUETAS SANGUE,"201,00"
3,2021-10-24 00:33:00,50,25722538,M,PLAQUETAS SANGUE,"319,00"
4,2021-10-24 00:33:00,19,20850235,F,NEUTRÓFILOS ABSOLUTO,"9,9006"
...,...,...,...,...,...,...
69438,2021-12-10 05:44:00,52,14708160,F,PLAQUETAS SANGUE,"172,00"
69439,2021-12-10 05:44:00,52,14708160,F,NEUTRÓFILOS ABSOLUTO,"10,4661"
69440,2021-12-10 05:44:00,52,14708160,F,LINFÓCITOS ABSOLUTO,"0,3609"
69441,2021-12-10 05:44:00,52,14708160,F,NEUTRÓFILOS %,"87,0"
69442,2021-12-10 05:44:00,52,14708160,F,LINFÓCITOS %,"3,0"

In [34]:
categorical_columns = list(df1.dtypes[df1.dtypes == 'str'].index)

for categorical_column in categorical_columns:
    df1[categorical_column] = df1[categorical_column].str.lower().str.replace(' ', '_')

In [35]:
df1

,date_time,age,patient_id,gender,plaquetas_sangue,"316,00"
0,2021-10-24_00:33:00,70,16084789,m,plaquetas_sangue,"239,00"
1,2021-10-24_00:33:00,62,25926519,f,plaquetas_sangue,"166,00"
2,2021-10-24_00:33:00,49,20209887,m,plaquetas_sangue,"201,00"
3,2021-10-24_00:33:00,50,25722538,m,plaquetas_sangue,"319,00"
4,2021-10-24_00:33:00,19,20850235,f,neutrófilos_absoluto,"9,9006"
...,...,...,...,...,...,...
69438,2021-12-10_05:44:00,52,14708160,f,plaquetas_sangue,"172,00"
69439,2021-12-10_05:44:00,52,14708160,f,neutrófilos_absoluto,"10,4661"
69440,2021-12-10_05:44:00,52,14708160,f,linfócitos_absoluto,"0,3609"
69441,2021-12-10_05:44:00,52,14708160,f,neutrófilos_%,"87,0"
69442,2021-12-10_05:44:00,52,14708160,f,linfócitos_%,"3,0"

In [36]:
df1.rename(columns={'316,00': 'quantity'}, inplace=True)

In [37]:
df1

,date_time,age,patient_id,gender,plaquetas_sangue,quantity
0,2021-10-24_00:33:00,70,16084789,m,plaquetas_sangue,"239,00"
1,2021-10-24_00:33:00,62,25926519,f,plaquetas_sangue,"166,00"
2,2021-10-24_00:33:00,49,20209887,m,plaquetas_sangue,"201,00"
3,2021-10-24_00:33:00,50,25722538,m,plaquetas_sangue,"319,00"
4,2021-10-24_00:33:00,19,20850235,f,neutrófilos_absoluto,"9,9006"
...,...,...,...,...,...,...
69438,2021-12-10_05:44:00,52,14708160,f,plaquetas_sangue,"172,00"
69439,2021-12-10_05:44:00,52,14708160,f,neutrófilos_absoluto,"10,4661"
69440,2021-12-10_05:44:00,52,14708160,f,linfócitos_absoluto,"0,3609"
69441,2021-12-10_05:44:00,52,14708160,f,neutrófilos_%,"87,0"
69442,2021-12-10_05:44:00,52,14708160,f,linfócitos_%,"3,0"

In [38]:
df2

        2019-04-07 13:36:00  38  22536285  M      PLAQUETAS SANGUE  282,00
0       2019-04-07 13:36:00  38  22536285  M  NEUTRÓFILOS ABSOLUTO  5,8476
1       2019-04-07 13:36:00  38  22536285  M   LINFÓCITOS ABSOLUTO  3,1896
2       2019-04-07 13:36:00  38  22536285  M         NEUTRÓFILOS %    44,0
3       2019-04-07 13:36:00  38  22536285  M          LINFÓCITOS %    24,0
4       2019-10-12 12:53:00   7  25368842  M      PLAQUETAS SANGUE  268,00
...                     ...  ..       ... ..                   ...     ...
152918  2020-11-19 10:09:00  43  24249245  M      PLAQUETAS SANGUE  234,00
152919  2020-11-19 10:09:00  43  24249245  M  NEUTRÓFILOS ABSOLUTO  3,8994
152920  2020-11-19 10:09:00  43  24249245  M   LINFÓCITOS ABSOLUTO  1,8293
152921  2020-11-19 10:09:00  43  24249245  M         NEUTRÓFILOS %    59,9
152922  2020-11-19 10:09:00  43  24249245  M          LINFÓCITOS %    28,1

[152923 rows x 6 columns]

In [39]:
df2.rename(columns={'2019-04-07 13:36:00': 'date_time', '38': 'age', '22536285': 'patient_id', 'M': 'gender', '282,00': 'quantity'}, 
          inplace=True)

In [40]:
df2

,date_time,age,patient_id,gender,PLAQUETAS SANGUE,quantity
0,2019-04-07 13:36:00,38,22536285,M,NEUTRÓFILOS ABSOLUTO,"5,8476"
1,2019-04-07 13:36:00,38,22536285,M,LINFÓCITOS ABSOLUTO,"3,1896"
2,2019-04-07 13:36:00,38,22536285,M,NEUTRÓFILOS %,"44,0"
3,2019-04-07 13:36:00,38,22536285,M,LINFÓCITOS %,"24,0"
4,2019-10-12 12:53:00,7,25368842,M,PLAQUETAS SANGUE,"268,00"
...,...,...,...,...,...,...
152918,2020-11-19 10:09:00,43,24249245,M,PLAQUETAS SANGUE,"234,00"
152919,2020-11-19 10:09:00,43,24249245,M,NEUTRÓFILOS ABSOLUTO,"3,8994"
152920,2020-11-19 10:09:00,43,24249245,M,LINFÓCITOS ABSOLUTO,"1,8293"
152921,2020-11-19 10:09:00,43,24249245,M,NEUTRÓFILOS %,"59,9"
152922,2020-11-19 10:09:00,43,24249245,M,LINFÓCITOS %,"28,1"

In [42]:
categorical_columns_df2 = list(df2.dtypes[df2.dtypes == 'str'].index)

for categorical_column in categorical_columns_df2:
    df2[categorical_column] = df2[categorical_column].str.lower().str.replace(' ', '_')

In [43]:
df2

,date_time,age,patient_id,gender,PLAQUETAS SANGUE,quantity
0,2019-04-07_13:36:00,38,22536285,m,neutrófilos_absoluto,"5,8476"
1,2019-04-07_13:36:00,38,22536285,m,linfócitos_absoluto,"3,1896"
2,2019-04-07_13:36:00,38,22536285,m,neutrófilos_%,"44,0"
3,2019-04-07_13:36:00,38,22536285,m,linfócitos_%,"24,0"
4,2019-10-12_12:53:00,7,25368842,m,plaquetas_sangue,"268,00"
...,...,...,...,...,...,...
152918,2020-11-19_10:09:00,43,24249245,m,plaquetas_sangue,"234,00"
152919,2020-11-19_10:09:00,43,24249245,m,neutrófilos_absoluto,"3,8994"
152920,2020-11-19_10:09:00,43,24249245,m,linfócitos_absoluto,"1,8293"
152921,2020-11-19_10:09:00,43,24249245,m,neutrófilos_%,"59,9"
152922,2020-11-19_10:09:00,43,24249245,m,linfócitos_%,"28,1"

In [44]:
df2.columns = df2.columns.str.lower().str.replace(' ', '_')

In [45]:
df2

,date_time,age,patient_id,gender,plaquetas_sangue,quantity
0,2019-04-07_13:36:00,38,22536285,m,neutrófilos_absoluto,"5,8476"
1,2019-04-07_13:36:00,38,22536285,m,linfócitos_absoluto,"3,1896"
2,2019-04-07_13:36:00,38,22536285,m,neutrófilos_%,"44,0"
3,2019-04-07_13:36:00,38,22536285,m,linfócitos_%,"24,0"
4,2019-10-12_12:53:00,7,25368842,m,plaquetas_sangue,"268,00"
...,...,...,...,...,...,...
152918,2020-11-19_10:09:00,43,24249245,m,plaquetas_sangue,"234,00"
152919,2020-11-19_10:09:00,43,24249245,m,neutrófilos_absoluto,"3,8994"
152920,2020-11-19_10:09:00,43,24249245,m,linfócitos_absoluto,"1,8293"
152921,2020-11-19_10:09:00,43,24249245,m,neutrófilos_%,"59,9"
152922,2020-11-19_10:09:00,43,24249245,m,linfócitos_%,"28,1"

In [46]:
df3

        2021-07-24 00:18:00  73  25834403  M      PLAQUETAS SANGUE  403,00
0       2021-07-24 00:18:00  73  25834403  M  NEUTRÓFILOS ABSOLUTO  2,9153
1       2021-07-24 00:18:00  73  25834403  M   LINFÓCITOS ABSOLUTO  1,8109
2       2021-07-24 00:18:00  73  25834403  M         NEUTRÓFILOS %    29,3
3       2021-07-24 00:18:00  73  25834403  M          LINFÓCITOS %    18,2
4       2021-07-24 00:19:00  17  25848842  F      PLAQUETAS SANGUE  321,00
...                     ...  ..       ... ..                   ...     ...
134477  2021-12-03 09:31:00  25  24766171  M      PLAQUETAS SANGUE   58,00
134478  2021-12-03 09:31:00  25  24766171  M  NEUTRÓFILOS ABSOLUTO  1,2600
134479  2021-12-03 09:31:00  25  24766171  M   LINFÓCITOS ABSOLUTO  1,3104
134480  2021-12-03 09:31:00  25  24766171  M         NEUTRÓFILOS %    45,0
134481  2021-12-03 09:31:00  25  24766171  M          LINFÓCITOS %    46,8

[134482 rows x 6 columns]

In [47]:
df3.columns = df3.columns.str.lower().str.replace(' ', '_')

In [48]:
df3

        2021-07-24_00:18:00  73  25834403  m      plaquetas_sangue  403,00
0       2021-07-24 00:18:00  73  25834403  M  NEUTRÓFILOS ABSOLUTO  2,9153
1       2021-07-24 00:18:00  73  25834403  M   LINFÓCITOS ABSOLUTO  1,8109
2       2021-07-24 00:18:00  73  25834403  M         NEUTRÓFILOS %    29,3
3       2021-07-24 00:18:00  73  25834403  M          LINFÓCITOS %    18,2
4       2021-07-24 00:19:00  17  25848842  F      PLAQUETAS SANGUE  321,00
...                     ...  ..       ... ..                   ...     ...
134477  2021-12-03 09:31:00  25  24766171  M      PLAQUETAS SANGUE   58,00
134478  2021-12-03 09:31:00  25  24766171  M  NEUTRÓFILOS ABSOLUTO  1,2600
134479  2021-12-03 09:31:00  25  24766171  M   LINFÓCITOS ABSOLUTO  1,3104
134480  2021-12-03 09:31:00  25  24766171  M         NEUTRÓFILOS %    45,0
134481  2021-12-03 09:31:00  25  24766171  M          LINFÓCITOS %    46,8

[134482 rows x 6 columns]

In [49]:
df3.rename(columns={'2021-07-24_00:18:00': 'date_time', '73': 'age', '25834403': 'patient_id', 'm': 'gender', '403,00': 'quantity'}, inplace=True)

In [50]:
df3

,date_time,age,patient_id,gender,plaquetas_sangue,quantity
0,2021-07-24 00:18:00,73,25834403,M,NEUTRÓFILOS ABSOLUTO,"2,9153"
1,2021-07-24 00:18:00,73,25834403,M,LINFÓCITOS ABSOLUTO,"1,8109"
2,2021-07-24 00:18:00,73,25834403,M,NEUTRÓFILOS %,"29,3"
3,2021-07-24 00:18:00,73,25834403,M,LINFÓCITOS %,"18,2"
4,2021-07-24 00:19:00,17,25848842,F,PLAQUETAS SANGUE,"321,00"
...,...,...,...,...,...,...
134477,2021-12-03 09:31:00,25,24766171,M,PLAQUETAS SANGUE,"58,00"
134478,2021-12-03 09:31:00,25,24766171,M,NEUTRÓFILOS ABSOLUTO,"1,2600"
134479,2021-12-03 09:31:00,25,24766171,M,LINFÓCITOS ABSOLUTO,"1,3104"
134480,2021-12-03 09:31:00,25,24766171,M,NEUTRÓFILOS %,"45,0"
134481,2021-12-03 09:31:00,25,24766171,M,LINFÓCITOS %,"46,8"

In [51]:
categorical_columns_df3 = list(df3.dtypes[df3.dtypes == 'str'].index)

for categorical_column in categorical_columns_df3:
    df3[categorical_column] = df3[categorical_column].str.lower().replace(' ', '_')

In [52]:
df3

,date_time,age,patient_id,gender,plaquetas_sangue,quantity
0,2021-07-24 00:18:00,73,25834403,m,neutrófilos absoluto,"2,9153"
1,2021-07-24 00:18:00,73,25834403,m,linfócitos absoluto,"1,8109"
2,2021-07-24 00:18:00,73,25834403,m,neutrófilos %,"29,3"
3,2021-07-24 00:18:00,73,25834403,m,linfócitos %,"18,2"
4,2021-07-24 00:19:00,17,25848842,f,plaquetas sangue,"321,00"
...,...,...,...,...,...,...
134477,2021-12-03 09:31:00,25,24766171,m,plaquetas sangue,"58,00"
134478,2021-12-03 09:31:00,25,24766171,m,neutrófilos absoluto,"1,2600"
134479,2021-12-03 09:31:00,25,24766171,m,linfócitos absoluto,"1,3104"
134480,2021-12-03 09:31:00,25,24766171,m,neutrófilos %,"45,0"
134481,2021-12-03 09:31:00,25,24766171,m,linfócitos %,"46,8"